services:
  couchdb:
    image: couchdb
    container_name: couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASS:-password}
    volumes:
      - ./data/coubchdb:/opt/couchdb/data
    ports:
      - 5984:5984
