services:
  termbridge:
    container_name: termbridge
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASS:-password}
    ports:
      - 3000:3000
  couchdb:
    image: couchdb
    container_name: couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASS:-password}
    volumes:
      - ./data/coubchdb:/opt/couchdb/data
    ports:
      - 5984:5984
